### ISSUE TITLE
Is there a tall variant?

### ISSUE THREAD

**Issue by DogLooksGood** [AndrewMontagne/TeleSys#1]
Hi, @AndrewMontagne , thanks for the great work on telesys.

I see there's tall variant in picture, is it available?

**Comment by AndrewMontagne** [comment]
Hi! The tall variant is located in the private use area of Unicode. I have followed the same code points as the wonderful fellows at galax.xyz, and you can find the documentation for their font at: http://www.galax.xyz/TELETEXT/INDEX.HTM

**Comment by DogLooksGood** [comment]
Thanks for the answer!

But, It seems I don't have enough knowledge about font. 
I want use a tall variant in code editor, and editor usually just accept the font name.  What should I do to have a tall version TTF, so that I can give editor a `Telesys Tall`?

**Comment by AndrewMontagne** [comment]
Sorry for the delay, @DogLooksGood! I apparrently don't get emails about replies.

You'd have to open up the font in FontForge and scale all the symbols by 200% vertically, tweak the font metrics for height, and then export it again.

**Comment by DogLooksGood** [comment]
Okay, thanks! This is not too hard for me:)
